name: NX-FanControl CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Mark git repository as safe
        run: git config --global --add safe.directory $PWD

      - name: Build
        run: |
          make all

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: NX-FanControl-Package
          path: |
            out/
            sysmodule/sysmodule.elf
            sysmodule/sysmodule.nsp
            overlay/overlay.elf
            overlay/overlay.ovl
            lib/libfancontrol/libfancontrol.a
          include-hidden-files: true
          if-no-files-found: warn
